name: CI Build
on: push
jobs:
  build-test:
    runs-on: self-hosted
    env:
      JAVA_HOME: /usr/lib/jvm/jdk1.8.0_301/
    steps:
      - uses: actions/checkout@v2
      - name: Build and install with maven
        run: mvn install
  deploy:
    runs-on: self-hosted
    env:
      JAVA_HOME: /usr/lib/jvm/jdk1.8.0_301/
    needs: build-test
    if: github.ref == 'refs/heads/main' # only run deploy on main branch
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: bash .github/deployment/deploy.sh